meta_product_name: "Backhand"
meta_title: "Backhand - Play More. Play Better. Rank Higher."
meta_description: "Backhand helps you find tennis players of your level everywhere. Find, play, and get your unique international ranking!"
meta_image: "backhand-banner.jpg" # should exist in `app/assets/images/`
