meta_product_name: "Backhand"
meta_title: "Backhand - Challenge tennis players everywhere"
meta_description: "Backhand helps you find tennis players of your level everywhere. Challenge, play, and get your unique international ranking!"
meta_image: "backhand_fb_banner.png" # should exist in `app/assets/images/`
